# Example DataNode for S3
apiVersion: kubedal.arunaengine.org/v1alpha1
kind: DataNode
metadata:
  name: example-s3-node
  namespace: default
  labels:
    region: us-east
spec:
  backend: S3 # Currently only S3 and HTTP are supported
  read_only: false
  limit: 10G
  # You can specify any valid OpenDAL configuration entries either:
  # 1. Directly in the config field
  # 2. As a key/values in the referenced Secret (for sensitive information)
  secretRef:
    name: s3-credentials
    namespace: default
  config:
    bucket: my-bucket
    endpoint: http://minio-service.default.svc.cluster.local:9000
    region: us-east-1
---
# Example DataNode for S3
apiVersion: kubedal.arunaengine.org/v1alpha1
kind: DataNode
metadata:
  name: replica-node-01
  namespace: default
  labels:
    region: eu-central
spec:
  backend: S3 # Currently only S3 and HTTP are supported
  read_only: true
  #limit: 10G
  # You can specify any valid OpenDAL configuration entries either:
  # 1. Directly in the config field
  # 2. As a key/values in the referenced Secret (for sensitive information)
  secretRef:
    name: s3-credentials
    namespace: default
  config:
    bucket: some-replica
    endpoint: http://minio-service.default.svc.cluster.local:9000
    region: us-east-1
---
# Example DataNode for S3
apiVersion: kubedal.arunaengine.org/v1alpha1
kind: DataNode
metadata:
  name: replica-node-02
  namespace: default
  labels:
    region: eu-central
spec:
  backend: S3 # Currently only S3 and HTTP are supported
  read_only: true
  #limit: 10G
  # You can specify any valid OpenDAL configuration entries either:
  # 1. Directly in the config field
  # 2. As a key/values in the referenced Secret (for sensitive information)
  secretRef:
    name: s3-credentials
    namespace: default
  config:
    bucket: another-replica
    endpoint: http://minio-service.default.svc.cluster.local:9000
    region: us-east-1

---
# Example Secret with credentials
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: default
type: Kubedal
stringData:
  access_key_id: "minioadmin" # Must be exactly as defined in the opendal config
  secret_access_key: "minioadmin" # Must be exactly as defined in the opendal config
---
# Example PVC that references the resource
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-dataset-pvc
  namespace: default
  annotations:
    kubedal.arunaengine.org/data-node-name: example-s3-node #TODO: Remove -> Use dataNodeRef in DataPod spec
    kubedal.arunaengine.org/data-node-namespace: default    #TODO: Remove -> Use dataNodeRef in DataPod spec
    kubedal.arunaengine.org/data-pod-name: example-data-pod
    kubedal.arunaengine.org/data-pod-namespace: default
    kubedal.arunaengine.org/mount: fuse-read-write
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: kubedal
  resources:
    requests:
      storage: 5Gi
---
# Example DataReplicaset that creates replicas with synced data of example-data-pod
apiVersion: kubedal.arunaengine.org/v1alpha1
kind: DataReplicaSet
metadata:
 name: example-data-replica-set
 namespace: default
 labels:
   foo: bar
spec:
 replicas: 2
 selector:
   matchLabels:
     foo: bar
 sourceDataPodRef:
   name: example-data-pod
   namespace: default
 template:
   metadata:
     labels:
       foo: bar
   spec:
     path: /sync-data
