# Example Datasource for S3
apiVersion: kubedal.arunaengine.org/v1alpha1
kind: Datasource
metadata:
  name: example-s3-dataset
spec:
  backend: S3 # Currently only S3 and HTTP are supported
  access_mode: ReadOnly # Can be ReadOnly or ReadWrite
  mount: Cached # Can be Cached or Fuse
  # You can specify any valid OpenDAL configuration entries either:
  # 1. Directly in the config field
  # 2. As a key/values in the referenced Secret (for sensitive information)
  credentials:
    secretRef:
      name: s3-credentials
      namespace: default
  config:
    bucket: my-bucket
    endpoint: http://localhost:9000
    region: us-east-1
    root: /foo/bar/my-root/
    enable_virtual_host_style: "true"
---
# Example Secret with credentials
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: default
type: Kubedal
stringData:
  access_key_id: "YOUR_ACCESS_KEY" # Must be exactly as defined in the opendal config
  secret_access_key: "YOUR_SECRET_KEY" # Must be exactly as defined in the opendal config
---
# Example PVC that references the resource
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-dataset-pvc
  namespace: default
  annotations:
    kubedal.arunaengine.org/datasource: example-s3-dataset
    kubedal.arunaengine.org/namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: kubedal
  resources:
    requests:
      storage: 10Gi
---
# Example Pod that uses the PVC
apiVersion: v1
kind: Pod
metadata:
  name: example-consumer
  namespace: default
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: dataset
          mountPath: /data
          readOnly: true
  volumes:
    - name: dataset
      persistentVolumeClaim:
        claimName: example-dataset-pvc
