# Example Datasource for S3
apiVersion: kubedal.arunaengine.org/v1alpha1
kind: Datasource
metadata:
  name: example-s3-dataset
spec:
  backend: S3 # Currently only S3 and HTTP are supported
  access_mode: ReadOnly # Can be ReadOnly or ReadWrite
  mount: Fuse # Can be Cached or Fuse
  # You can specify any valid OpenDAL configuration entries either:
  # 1. Directly in the config field
  # 2. As a key/values in the referenced Secret (for sensitive information)
  credentials:
    secretRef:
      name: s3-credentials
      namespace: default
  config:
    bucket: my-bucket
    endpoint: http://minio-service:9000
    region: us-east-1
    enable_virtual_host_style: "true"
---
# Example Secret with credentials
apiVersion: v1
kind: Secret
metadata:
  name: s3-credentials
  namespace: default
type: Kubedal
stringData:
  access_key_id: "minioadmin" # Must be exactly as defined in the opendal config
  secret_access_key: "minioadmin" # Must be exactly as defined in the opendal config

---
# Example Minio Deployment and Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: minio/minio:latest
        args:
        - server
        - /data
        ports:
        - containerPort: 9000
          hostPort: 9000          
---
apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  type: ClusterIP
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
  selector:
    app: minio
---
# Example PVC that references the resource
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-dataset-pvc
  namespace: default
  annotations:
    kubedal.arunaengine.org/datasource: example-s3-dataset
    kubedal.arunaengine.org/namespace: default
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: kubedal
  resources:
    requests:
      storage: 10Gi
---
# Example Pod that uses the PVC
apiVersion: v1
kind: Pod
metadata:
  name: example-consumer
  namespace: default
spec:
  containers:
    - name: app
      image: alpine
      command: ["sleep", "infinity"]
      volumeMounts:
        - name: dataset
          mountPath: /data
          readOnly: true
  volumes:
    - name: dataset
      persistentVolumeClaim:
        claimName: example-dataset-pvc